"""create_journey_tables

Revision ID: b1b405869802
Revises: 
Create Date: 2026-08-28 03:51:38.612144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b405869802'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('objective_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('journey_id')
    )
    op.create_table('audit_entries',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('authorisation_outcomes',
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('request_desc', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('recorded_by', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_table('held_identifiers',
    sa.Column('identifier_id', sa.String(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('issued_at', sa.String(), nullable=False),
    sa.Column('stale_after_seconds', sa.Integer(), nullable=False),
    sa.Column('stale_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('identifier_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('held_identifiers')
    op.drop_table('authorisation_outcomes')
    op.drop_table('audit_entries')
    op.drop_table('journeys')
    # ### end Alembic commands ###
